apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: iad.ocir.io/ax022wvgmjpq/oke-canary-poc/guestbook-final-repo:${version}
        name: guestbook
        env:
          - name: REDIS_HOST
            value: ${redis_host}

---

apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  type: ClusterIP  
  ports:
  - name: guestbook
    port: 8080
  selector:
    app: guestbook

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poc-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: poc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guestbook
                port:
                  number: 8080